CREATE
  (jim:Developer:Happy {name:'Jim', id:'2bf37261-30bf-4de5-bcdf-28b579c9fe02'}),
  (martin:Developer:RegretsLifeDecisions {name:'Martin', id:'b4c2b7e0-eeb1-4b9e-9e4c-6e9c9f1f8d8a'}),
  (phil:Developer:Happy {name:'Phil', id:'c2b7e0b4-eeb1-4b9e-9e4c-6e9c9f1f8d8a'}),
  (thomas:Developer:Happy {name:'Thomas', id:'b7e0b4c2-eeb1-4b9e-9e4c-6e9c9f1f8d8a'}),
  (salli:Developer:Happy {name:'Salli', id:'e0b4c2b7-eeb1-4b9e-9e4c-6e9c9f1f8d8a'}),
  (project_one:Project {name:'Project One', deadline:'2022-01-01T12:00:00Z', metadata: '{\"awesome\": true}', milestones: ['{\"name\": \"That hard thing done\", \"timestamp\": 1691696518}']}),
  (project_two:Project {name:'Project Two', deadline:'2022-04-23T16:45:00Z', metadata: '{}', milestones: ['{\"name\": \"Finished talking with important person\", \"timestamp\": 1691825684}', '{\"name\": \"Got copilot to do the work for me\", \"timestamp\": 1691682690}']}),
  (macchiato:Coffee {flavour:'Macchiato', origin:'Italy'}),
  (espresso:Coffee {flavour:'Espresso', origin:'Colombia'}),
  (dark_roast:Coffee {flavour:'Dark Roast', origin:'Brazil'}),
  (jim)-[:WORKS_ON {role:'Lead'}]->(project_one),
  (jim)-[:WORKS_ON {role:'Developer'}]->(project_two),
  (martin)-[:WORKS_ON {role:'Developer'}]->(project_one),
  (phil)-[:WORKS_ON {role:'Intern'}]->(project_two),
  (salli)-[:WORKS_ON {role:'Lead'}]->(project_two),
  (jim)-[:IMPLEMENTED {name:'Implemented the thing', amount_of_bugs: 3}]->(project_one),
  (jim)-[:IMPLEMENTED {name:'Some more things', amount_of_bugs: 5}]->(project_one),
  (jim)-[:IMPLEMENTED {name:'Something veeeery important', amount_of_bugs: 0}]->(project_two),
  (martin)-[:IMPLEMENTED {name:'Implemented the other thing', amount_of_bugs: 29}]->(project_one),
  (salli)-[:IMPLEMENTED {name:'Serious work', amount_of_bugs: 7}]->(project_two),
  (martin)-[:HATED_BY]->(jim),
  (martin)-[:HATED_BY]->(phil),
  (martin)-[:HATED_BY]->(thomas),
  (martin)-[:HATED_BY]->(salli),
  (espresso)-[:CONSUMED_BY]->(jim),
  (espresso)-[:CONSUMED_BY]->(martin),
  (dark_roast)-[:CONSUMED_BY]->(phil),
  (macchiato)-[:CONSUMED_BY]->(phil)
